### ISSUE TITLE
Icons disappear on Mac

### ISSUE THREAD

**Issue by sentient06** [ScottMichaud/LighterWTAustralis#1]
This extension makes invisible some of the icons native to Firefox. Testing on version 55.0.2 for Macintosh.

![screen shot 2017-08-18 at 10 41 36](https://user-images.githubusercontent.com/1292694/29453567-f8528d9a-8401-11e7-90fb-a38ee93b7028.png)

**Comment by ScottMichaud** [comment]
Unfortunately, Mozilla is going to remove the entire add-on architecture in Firefox 57. This add-on will not work at all by the end of November. Also, the new API, called WebExtensions, is more limited, especially for things that modify the browser's theme. AFAIK this add-on cannot be written in the new framework (although it's possible that the API could expand in the future).

Sorry for the inconvenience! At one point, I actually disabled it in the add-ons list to prevent new installs, but re-listed it when it started retroactively uninstalling existing users.

**Comment by ScottMichaud** [comment]
The API that this extension requires does not exist anymore.
